### ISSUE TITLE
Bogus date in %changelog directive in rpm SPEC file

### ISSUE THREAD

**Issue by naoyuki-mori** [intel/qatlib#10]
Dated backward in %changelog directive causing rpmbuild error.

```
$ rpmbuild -ba qatlib.spec
warning: bogus date in %changelog: Wed Jun 14 2021 Marcin Malinowski <marcinx.malinowski@intel.com> - 22.07-0-1
error: %changelog not in descending chronological order
```

**Comment by gcabiddu** [comment]
Fixed in 22.07.01

**Comment by naoyuki-mori** [comment]
Thanks!
But still encounter rpm build issue, so will post as different issue soon.
